### ISSUE TITLE
this no longer works; library shows as empty and the only fix was to install the EA app

### ISSUE THREAD

**Issue by Druout** [p0358/Fuck_off_EA_App#41] opened 2024-03-19 20:05 UTC
### Checklist

- [X] I ensured I'm running the [latest version of the patch](https://github.com/p0358/Fuck_off_EA_App/releases), and that the issue is present in it if applicable
- [X] I have read the entirety of the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq) section in the readme, and my question was not answered there, or was not answered sufficiently
- [X] I have ran general troubleshooting steps (if applicable), such as restarting the PC/reinstalling Origin/whatever else is described in the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq), and they didn't help
- [X] I have checked [existing issues](https://github.com/p0358/Fuck_off_EA_App/issues?q=is%3Aissue) (including closed ones), and there wasn't an existing issue pertaining to my problem (with possible solutions in the comments)

### Your issue

2 days ago this no longer worked; my origin library shows as empty and the only fix was to install the EA app. Issue was replicated on 6 of PCs with origin installed using your latest build of the EA app bypass program.

**Comment by p0358** [comment] 2024-03-19 20:07
Yeah, this was a temporary outage on EA's side and now it should be working again, duplicate of #40

**Closed by p0358** 2024-03-19 20:07 UTC
Labels: duplicate
