### ISSUE TITLE
Working configuration broke?

### ISSUE THREAD

**Issue by Doc-4** [p0358/Fuck_off_EA_App#40] opened 2024-03-18 18:51 UTC
### Checklist

- [X] I ensured I'm running the [latest version of the patch](https://github.com/p0358/Fuck_off_EA_App/releases), and that the issue is present in it if applicable
- [X] I have read the entirety of the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq) section in the readme, and my question was not answered there, or was not answered sufficiently
- [X] I have ran general troubleshooting steps (if applicable), such as restarting the PC/reinstalling Origin/whatever else is described in the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq), and they didn't help
- [X] I have checked [existing issues](https://github.com/p0358/Fuck_off_EA_App/issues?q=is%3Aissue) (including closed ones), and there wasn't an existing issue pertaining to my problem (with possible solutions in the comments)

### Your issue

I ran an existing instance of this in sandboxie a few weeks ago and it was working fine, same instance today I get a message about it being unable to load my library and origin trying to open a webpage, which either is or redirects to the EA app page. Possibly broken again?

**Comment by Hexaae** [comment] 2024-03-18 19:09
Same here. Error opening my library or even my user profile from old client patched.

**Comment by p0358** [comment] 2024-03-18 19:40
Hmm, it seems that loading the games library doesn't work. But doesn't booting up the game from Start Menu/right click still work? I just tested on my still-running Origin instance and it logs me into booted-up games.

However, EA messing with game library APIs might mean that end of Origin is soon, at least for those who don't have the games installed already. Perhaps the best bet would be having both EA App and Origin at once...

**Comment by Hexaae** [comment] 2024-03-18 21:55
Ok, just tried current EA App (over-install, I didn't remove Origin patched first)... everything seems to be working fine and the App is actually improved a lot. All my games are in the Library, I can define launch parameters for each game, online games like BF3 (which auto launches the Edge browser and logs in on Battlelog) do work fine... so everything seems OK, finally. Garbage beta-level of early EA App release seems only an old nightmare.
Thank you p0358 for all your past work! 👍🏻

**Comment by xPixelGhost** [comment] 2024-03-18 21:59
Seen on origin's reddit someone mention a EA rep told them origin is down due to them working on upgrading the mac users to switch to EA app now so they must be working on patching out workarounds but who knows if it's true or not.

**Comment by p0358** [comment] 2024-03-19 07:39
Actually it seems to be back up and working again. Guess the userbase of Origin is still big enough they went ahead and fixed it up...?

**Comment by Hexaae** [comment] 2024-03-19 08:58
LOL... not the first time anyway. In the past it happened already for a few days and then worked again as usual...
However as far as I can see EA App is finally decent enough, and I see no real advantage in using Origin with its random blackouts.

**Comment by p0358** [comment] 2024-03-19 09:03
Unfortunately EA App still has its rough edges. For us it's the permanently broken inviting. Always works on Origin, doesn't work at all most of the time on EA App, people there cannot send invites and cannot accept them half of the time. Not to mention that on Origin you could just click on button next to friend to join them right up, while on EA App you NEED an explicit invite (but it's only a client-side limitation, so it hardly even meets the probable reason for making it this way).

So all in all I still think it's worthy to keep this thing around, though the good message is that afaik having both apps installed is just fine, so can always switch up if something doesn't work in one or the other...

Also, there's a group of people working on an open-source replacement similar to Legendary for Epic Games, quite hyped for that ngl (it's probably still gonna take some decent amount of time though)

**Comment by p0358** [comment] 2024-03-19 09:05
Either way, since the problem is gone and fixed by EA, I'm gonna close the issue for the time being.

**Closed by p0358** 2024-03-19 09:05 UTC

**Comment by Hexaae** [comment] 2024-03-19 09:07
Good to know, thanks. I have a backup of your patched files and the procedure to apply to the old Origin offline installer exe in case 😉

**Comment by p0358** [comment] 2024-03-19 09:13
Speaking of backups, one could have a backup of the JS/CSS files that Origin loads up, in case EA ever gets tempted to block/nuke them from the server instead of having their EA App message being implemented in JavaScript. I think I have one, though it'd still be under an unlikely scenario they'd do that while keeping the APIs up imo + would be annoying to develop a way to serve them instead, but might be good for archival purposes regardless...

But given they fixed the issue today, I don't think they are too hard pressed to force people off Origin unless they have to, they probably figured people have reasons for going this far to keep using it for the time being. Installer is still on CDN, APIs are still up and so on...

The broken update push-out many months ago was the last in the cat-and-mouse game so far

**Comment by Doc-4** [comment] 2024-03-19 11:04
For those of you who have used the EA app lately, have they fixed the issue it has with a lot of their older games of not even working with invites at all? Like there's a button to open the friends list to invite somebody in Mass Effect 3. In the original it works, the new overlay doesn't even open last I tried like 8 months ago

**Comment by Hexaae** [comment] 2024-03-19 12:57
Unfortunately I don't use those social features... I can see the list of friends online in the new EA App but never tried the invite thing...

**Comment by Hexaae** [comment] 2024-03-20 20:23
For the chronicles... it seems the Origin interface is still working because Origin is still available for Mac users.

**Comment by p0358** [comment] 2024-03-21 15:57
Of course, but time is ticking since they're making a Mac version of EA App now. And I've seen one report that someone got the nag to upgrade already, but idk how legit it might be. In any case, on my Mac Origin still works, but there's notice at the top that EA App will be there soon. Frankly it should be possible to make a similar patch for Mac, but not sure if I wanna waste my time on that. It'd require Xcode toolchain being installed too to re-sign the app.
