### ISSUE TITLE
Incompatable with the EA DLC Unlocker and vice versa

### ISSUE THREAD

**Issue by mason321** [p0358/Fuck_off_EA_App#15] opened 2023-07-10 19:40 UTC
### Checklist

- [X] I ensured I'm running the [latest version of the patch](https://github.com/p0358/Fuck_off_EA_App/releases), and that the issue is present in it if applicable
- [X] I have read the entirety of the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq) section in the readme, and my question was not answered there, or was not answered sufficiently
- [X] I have ran general troubleshooting steps (if applicable), such as restarting the PC/reinstalling Origin/whatever else is described in the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq), and they didn't help

### Your issue

for some reason I cannot have both of them installed and had to use one after the other

**Comment by p0358** [comment] 2023-07-11 07:21
Duplicate of #12, there's a workaround there in comments (maybe there'll be some way to chain-load other mods in some future update, but for now I'm not making v3 until the current version breaks again)

**Closed by p0358** 2023-07-11 07:21 UTC
