### ISSUE TITLE
EA is forcing to update the app

### ISSUE THREAD

**Issue by Coverop** [p0358/Fuck_off_EA_App#19] opened 2023-07-31 18:11 UTC
### Checklist

- [X] I ensured I'm running the [latest version of the patch](https://github.com/p0358/Fuck_off_EA_App/releases), and that the issue is present in it if applicable
- [X] I have read the entirety of the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq) section in the readme, and my question was not answered there, or was not answered sufficiently
- [X] I have ran general troubleshooting steps (if applicable), such as restarting the PC/reinstalling Origin/whatever else is described in the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq), and they didn't help
- [X] I have checked [existing issues](https://github.com/p0358/Fuck_off_EA_App/issues?q=is%3Aissue) (including closed ones), and there wasn't an existing issue pertaining to my problem (with possible solutions in the comments)

### Your issue

It seems that EA has found a way to force an update to this current version of Origin.

![NVIDIA_Share_9zbvjQJBmL](https://github.com/p0358/Fuck_off_EA_App/assets/8415531/353542f6-2d91-4094-9b92-396da10db177)

Attempting to update the software will cause an error and you'll get stuck in the loop of "Origin needing an update"

![NVIDIA_Share_4kDPxYXwX4](https://github.com/p0358/Fuck_off_EA_App/assets/8415531/a946d475-1b75-4a6b-a317-638a6a868637)

Reinstalling the software will give you a nice  "INSTALL EA" message indicating that EA does not tolerate Origin.

![NVIDIA_Share_kxBdALMtRj](https://github.com/p0358/Fuck_off_EA_App/assets/8415531/d92acb39-d5e2-4f28-ba79-d213446aa54a)

This is very dishearting to see greedy corpo going the extra step to kill a properly functional application.

**Comment by Gotfyr** [comment] 2023-07-31 18:59
I fixed this by adding
[Bootstrap]
EnableUpdating=false
in the EACore.ini file in C:\Program Files (X86)\Origin

See if it works for you

**Comment by DerMathze** [comment] 2023-07-31 19:19
> I fixed this by adding [Bootstrap] EnableUpdating=false in the EACore.ini file in C:\Program Files (X86)\Origin
> 
> See if it works for you

Thanks, that fixed it for me.

**Comment by p0358** [comment] 2023-07-31 20:00
Looks like they tried to push EA App install as Origin update but failed and currently the update download link that they provide doesn't work, thus the update error (it's evident by the "update" version being `12.244.0.5501`, which corresponds to latest EA App version...). For now recommend the steps above to disable updating, and I will probably soon release some update of the patch to block updates, just not sure if I should make it optional or forceful, and whether I should block all updates or just those that don't look valid. Probably safer to block all if this is the avenue they're trying to push now...

**Comment by Gamaramdi** [comment] 2023-07-31 22:53
Well that makes you reconsider if you're ever buying something from EA doesn't it?

**Comment by nonohama** [comment] 2023-08-02 05:55
> I fixed this by adding [Bootstrap] EnableUpdating=false in the EACore.ini file in C:\Program Files (X86)\Origin
> 
> See if it works for you

when i do that that error shown after iam going to open origin to sign in 
![fuckea](https://github.com/p0358/Fuck_off_EA_App/assets/141209836/33fa8da6-879e-4abb-ad1a-8e26358ae1b6)

**Comment by p0358** [comment] 2023-08-02 12:59
@nonohama what is your Origin version? It looks like it predates the migration feature completely, in which case it might mean the project here isn't even required for it (perhaps), at the same time newer Origin versions are better since they are prepared to handle being co-installed with EA App

**Comment by rubytook** [comment] 2023-08-02 21:31
Looks like it could be a non-Unicode version of Origin for foreign language systems?  *shrug*  All my non-Unicode programs use an older Windows style title bar and menus, but only a few of them are modern so I can't say if that's still true across the board.  But that looks translated, so maybe?  Not the OP, but thought I might mention it.  That could also mean that it's old as well, since I can't see EA being terribly accommodating on the program compatibility front.

**Comment by Druout** [comment] 2023-08-04 00:18
> I fixed this by adding [Bootstrap] EnableUpdating=false in the EACore.ini file in C:\Program Files (X86)\Origin
> 
> See if it works for you

You are a life saver good sir.

**Comment by EuropeanEnginner** [comment] 2023-08-04 06:16
I already put EnableUpdating=false on the EAcore. Is it safe to update it now?

**Comment by itsphilgeorge** [comment] 2023-08-09 00:34
Same as above. Have applied EACore.ini modification but cannot use Origin due to the forced upgrade prompt.

**Comment by mattrex8765** [comment] 2023-08-10 17:42
So... what's the current situation with this workaround? I'm tired of having to deal with those incompetent clowns at EA Answers HQ and EA Help.

**Comment by zyf722** [comment] 2023-08-14 14:21
> I fixed this by adding [Bootstrap] EnableUpdating=false in the EACore.ini file in C:\Program Files (X86)\Origin
> 
> See if it works for you

It seems this method doesn't work anymore now.

Able to launch BF1 yesterday, but today the annoying "Please use EA App to continue" tip appears again.

**Comment by p0358** [comment] 2023-08-14 19:56
Hm, I can't seem to be able to reproduce the issue above at all. Are you running the 122 or 119 version? I'll only be able to investigate this properly somewhere at the end of the week, I wonder if they did something funny if others get the prompt again and I don't...

**Comment by kidemperor** [comment] 2023-08-15 01:48
> > I fixed this by adding [Bootstrap] EnableUpdating=false in the EACore.ini file in C:\Program Files (X86)\Origin
> > See if it works for you
> 
> It seems this method doesn't work anymore now.
> 
> Able to launch BF1 yesterday, but today the annoying "Please use EA App to continue" tip appears again.

i just used this solution and it worked fine for me and I didn't get the ea app migration pop up either.  unfortunately I have no idea what would cause this on your end, best of luck

**Comment by zyf722** [comment] 2023-08-15 02:46
> Hm, I can't seem to be able to reproduce the issue above at all. Are you running the 122 or 119 version? I'll only be able to investigate this properly somewhere at the end of the week, I wonder if they did something funny if others get the prompt again and I don't...

I'm on 119 ver currently. Strangely I don't see any files updated in Origin folder based on their last modified time.

**Comment by itsphilgeorge** [comment] 2023-08-15 06:19
If no files have been updated on your filesystem, suggests this is something being pushed within the webloading section. Most likely occurs when we haven't blocked something correctly. Mine still doesn't work.

**Comment by levicki** [comment] 2023-08-29 22:25
This whole notion of web-browser-as-a-desktop-app has to die in a fire.

**Comment by Dajova** [comment] 2023-09-13 17:58
Im getting the same ("Please use the EA app" error) and the ini fix above doesnt seem to help either... and i cant install the EA app either cus i keep on getting a connection error, so i cant even use anyway... So if this doesnt work either, then i'm kinda screwed...

**Comment by Riddick-2K** [comment] 2023-09-16 14:03
HI.
Sorry for writing here, but I haven't found another way: how can I contribute materially to this project?
However, with version 119 and your library I can still play BFH, BF1 and BF5.
You are a savior and I hope you can keep it going as long as possible.
Thank you ! Thanks again ;-)

**Comment by alxmhn** [comment] 2023-09-21 03:17
On macOS, the "origin" Winetrick uses a version.dll mod to bypass the update popup and works fine. I'm not sure why this wouldn't work on Windows, though... Maybe Wine is doing something extra?

cc: @gcenx

<img width="1042" alt="Screenshot 2023-09-20 at 11 17 13 PM" src="https://github.com/p0358/Fuck_off_EA_App/assets/127183868/d13bcf7b-238b-451e-9bcf-6d5aa82844c5">

**Comment by levicki** [comment] 2023-09-21 12:05
Anyone who has a problem should:

1. Uninstall Origin
2. Download Origin from the link given in this project README
3. Install Origin
4. When prompted for sign in CLOSE Origin fully
5. Copy version.dll into Origin folder
6. Create (or edit if it exists) a file `EACore.ini` in Origin folder and make sure its contents are as follows:
    ```
    [Bootstrap]
    EnableUpdating=false
    ```
7. Start Origin
8. Sign in

It should work normally.

**Comment by FelixJongleur42** [comment] 2023-09-23 08:23
**Tried this App because it's supposed to be a workaround for EAFC24 launching issues.**

> Anyone who has a problem should:

I tried installer with these options, had to edit ini anyway.
![image](https://github.com/p0358/Fuck_off_EA_App/assets/19993980/58dd7c08-3a75-455c-99e7-c4b97594a270)

At 7 I still got the nag screen to update, but cancelled it.
At 8 the login dialog failed, had to start OriginWebHelperService manually.

**Now Origin is running (122) and it says** 
![image](https://github.com/p0358/Fuck_off_EA_App/assets/19993980/0c1adf6e-7293-4846-bed2-baf12109fcf8)
**in the caption.**

So maybe somewhere between 6 and 7, add the step to manually start OriginWebHelperService ? (since it needed to be stopped to install the dll?)

Got some errors about cloud sync but I ignored them reverted to local files.

Tried this App because it's supposed to be a workaround for EAFC24 launching issues. But it did not help (looks like the EA AntiCheat keeps crashing).

**Comment by levicki** [comment] 2023-09-23 22:39
> So maybe somewhere between 6 and 7, add the step to manually start OriginWebHelperService ? (since it needed to be stopped to install the dll?)

Origin works without OriginWebHelperService if you turn it off iin Origin settings. Of course, that's a chicken and egg problem &mdash; you can't configure it until you start it and login. I don't know if there is a way to include that setting by default somewhere (registry, or some config file).

**Comment by ujnor** [comment] 2023-09-26 12:32
> Anyone who has a problem should:
> 
> 1. Uninstall Origin
> 2. Download Origin from the link given in this project README
> 3. Install Origin from downloaded file
> 4. When prompted to sign in DO NOT SIGN IN AND CLOSE Origin FULLY
> 5. Copy `version.dll` into Origin folder next to `Origin.exe`
> 6. Create (or edit if it exists) a file `EACore.ini` in Origin folder and make sure its contents are as follows:
>    ```
>    [Bootstrap]
>    EnableUpdating=false
>    ```
> 7. Start Origin
> 8. Sign in
> 
> It should work normally.

Unfortunately, I tried it today, followed steps carefully and it didn't work for me 😭

**Comment by p0358** [comment] 2023-10-28 21:40
Should now be fixed in v3, feel free to reopen if not

> Sorry for writing here, but I haven't found another way: how can I contribute materially to this project?

@Riddick-2K I've added donate link to the readme now based on this suggestion, also gonna paste here: https://www.paypal.me/p0358donate

Thank you for all the support and please let me know if anything is still broken

**Closed by p0358** 2023-10-28 21:40 UTC

**Comment by shoushou1106** [comment] 2023-11-05 06:05
> Should now be fixed in v3, feel free to reopen if not  
  
how to update? Run the installer again?

**Comment by p0358** [comment] 2023-11-05 15:31
Yeah

**Comment by alireza-nouri** [comment] 2023-11-05 22:43
Anyone experiencing the issue should check this link and follow the steps after step 10
https://github.com/Whisky-App/Whisky/issues/272#issue-1827906027

**Comment by Riddick-2K** [comment] 2023-11-12 21:28
Excellent, thanks...
I sent some money in €. You should receive them from a
"bas-eta@**********" (email from an Italian provider that I don't
mention in the public email).
If I knew how to send you a private message on GitHub, I would have done it.
Thanks again for this project of yours, it was a lifesaver for me...
Origin works normally for me, thanks to you. The EA APP is shit and I
don't even have my old games in it anymore...
Please... do everything you can to carry forward this project of yours.
Best wishes for everything, even in your normal life.

Davide.

2023-10-28 23:40 GMT+02:00, p0358 ***@***.***>:
