### ISSUE TITLE
Doesn't work with EA DLC Unlocker

### ISSUE THREAD

**Issue by apolloreyes** [p0358/Fuck_off_EA_App#37] opened 2024-02-17 19:03 UTC
### Checklist

- [x] I ensured I'm running the [latest version of the patch](https://github.com/p0358/Fuck_off_EA_App/releases), and that the issue is present in it if applicable
- [X] I have read the entirety of the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq) section in the readme, and my question was not answered there, or was not answered sufficiently
- [X] I have ran general troubleshooting steps (if applicable), such as restarting the PC/reinstalling Origin/whatever else is described in the [FAQ](https://github.com/p0358/Fuck_off_EA_App#faq), and they didn't help
- [X] I have checked [existing issues](https://github.com/p0358/Fuck_off_EA_App/issues?q=is%3Aissue) (including closed ones), and there wasn't an existing issue pertaining to my problem (with possible solutions in the comments)

### Your issue

When I install EA DLC Unlocker, it makes origin go back to "download EA app"

**Comment by p0358** [comment] 2024-02-17 19:18
Duplicate of #12

**Closed** 2024-02-17 19:18 UTC
